spring:
  application:
    name: EventClean

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.driver

  jpa:
    show-sql: true

  flyway:
    enabled: true